version: "3.4"
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./session:/data
    command: redis-server --save 60 1
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Kolkata"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      TZ: "Asia/Kolkata"