version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
