version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

  # Node.js application service
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Guardian
    depends_on:
      - redis
    ports:
      - "8000:8000"

    env_file:
      - .env
