version: "3.4"
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./session:/data
    command: redis-server --save 60 1
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Kolkata"
    restart: always

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      TZ: "Asia/Kolkata"
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS: '{"useUnifiedTopology":true}'
    ports:
      - "8082:8081"
    depends_on:
      - mongodb
    restart: always