version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Guardian
    depends_on:
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
