version: "3.4"
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./sessionData:/data
    command: redis-server --save 60 1
    ports:
      - "6379:6379"
    environment:
      TZ: "Asia/Kolkata"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    restart: always
    environment:
      TZ: "Asia/Kolkata"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Backend
    depends_on:
      - redis
      - mongodb
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/node_modules
    environment:
      TZ: "Asia/Kolkata"

  client:
    container_name: Frontend
    depends_on:
      - server
    build:
      context: ./Guardian-Frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./Guardian-Frontend:/usr/src/app
      - /usr/src/node_modules
    environment:
      TZ: "Asia/Kolkata"
